### ISSUE TITLE
Android unable to perform verification after exiting screen

### ISSUE THREAD

**Issue by sofiac-developer** [stripe/stripe-identity-react-native#101]
Bug Summary

On Android, when I generate the verificationSession through our backend and call present() to pop-up the screen, it works initially. However, if I don't complete the request and back out of the screen, and then go back into the screen, I'm presented with a different screen that has a single button that says "GET STARTED" at the bottom. 

This issue doesn't seem to occur on iOS since when I back out of completing the verification, and go back in, it takes me directly to the screen to ask me to provide a documentation type. 

Is this a bug with the library or do we need to regenerate a new verification session if the user decides to back out of completing the verification?

Library Versions
stripe-identity: 0.1.1
react-native: 0.71.3

**Comment by ccen-stripe** [comment]
hi @sofiac-developer could you verify if you're using id/address/phone verification type? The native SDK doesn't have support to these type yet and the "Get started" screen was a fallback flow to web.  

We just released [0.1.4](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.4) to support ID/Address verification type, could you try update to the new version?

**Comment by ccen-stripe** [comment]
Closing the issue for now, feel free to reopen if you still see issues
