### ISSUE TITLE
No screen to handle missing id_number

### ISSUE THREAD

**Issue by giaset** [stripe/stripe-identity-react-native#102]
Hey there,

We go through the flow and capture front/back of drivers license, followed by the selfies. When we try to continue to the next screen, we get a `noScreenForRequirements` error. I've dug in to the code and there is no case to handle when `missingRequirements` contains `idNumber`.

It seems like the latest version of `VerificationSheetFlowController.swift` in the `stripe-ios` has such a case. Is this library on an outdated version of the pod?

<img width="1580" alt="Screen Shot 2023-03-07 at 6 07 23 PM" src="https://user-images.githubusercontent.com/2816603/223600964-6f63baa6-3b0c-4cd1-a8e8-532597386eab.png">

**Comment by giaset** [comment]
Got it working by updating the dependency in the podspec from StripeIdentity 23.3.0 to 23.4.2.

Was this screen just not implemented in the previous version of the SDK?

![image](https://user-images.githubusercontent.com/2816603/223626975-62868d9c-d92b-443d-9348-30368c6cd947.png)

**Comment by ccen-stripe** [comment]
hi @giaset, thanks for reaching out. Yes, id number support is added in 23.4.2 in iOS - could you clarify your environment(stripe-identity-react-native version, iOS SDK version) and how the verification session session is created?

I just tried to build our [test RN app](https://github.com/stripe/stripe-identity-react-native/tree/main/example/ios) with iOS version 23.3.0 and it falls back to the webview, which has support for id number.
<img width="403" alt="Screen Shot 2023-03-08 at 12 09 26 PM" src="https://user-images.githubusercontent.com/79880926/223837519-35dca63c-b351-485a-847a-0aa2d002858e.png">

**Comment by ccen-stripe** [comment]
thanks for the update, yeah confirmed this is not supported in `23.3.4`, we'll release a new react native version to fix this soon

**Comment by ccen-stripe** [comment]
to be fixed in 0.1.3: https://github.com/stripe/stripe-identity-react-native/pull/103
