### ISSUE TITLE
Package not downloading. Json file in node_module contains this message

### ISSUE THREAD

**Issue by burhanahmedsiddiqi** [stripe/stripe-identity-react-native#108]
This package contained malicious code and was removed from the registry by the npm security team. A placeholder was published to ensure users are not affected in the future.

**Comment by ccen-stripe** [comment]
hi @burhanahmedsiddiqi could you double check you environment and use the latest release? I just tried with [0.1.4](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.4) and was able to build successfully.

Also you could try build the test app by checking out the repository and run `yarn android` or `yarn ios` under [this](https://github.com/stripe/stripe-identity-react-native/tree/main/example) dir.

**Comment by ccen-stripe** [comment]
feel free to reopen if it still persists
