### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by burhanahmedsiddiqi** [stripe/stripe-identity-react-native#109]
After linking package successfully it returns this error on build:

`Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">`

How to fix this

**Comment by ccen-stripe** [comment]
hi @burhanahmedsiddiqi this doesn't seem from the react native SDK, but from something with your local android dev environment, please refer to [this](https://stackoverflow.com/questions/74191324/cant-determine-type-for-tag-macro-name-m3-comp-bottom-app-bar-container-colo) thread for more details

**Comment by hsb1007** [comment]
I have the same issue..

**Comment by hsb1007** [comment]
Yes I managed to get it working after upgrading gradle on Android Studio! 

Thanks

**Comment by jyo142** [comment]
hi @hsb1007 I am experiencing the same issue as well. what did you upgrade exactly to get it working? Thank you

**Comment by hsb1007** [comment]
> 

When I went into Tools > AGP Upgrade Asistant within Android Studio, it prompted me to upgrade my Gradle to 7.x.

Hope it works for you too!
