### ISSUE TITLE
The package 'stripe-identity-react-native' doesn't seem to be linked. Expo managed workflow

### ISSUE THREAD

**Issue by ribbonhood** [stripe/stripe-identity-react-native#113]
How can I get this to work with expo in a managed workflow? I'm using expo 47.0.14 with react-native 0.70.8

I get the following error when I try to run an example,
```
Error: The package 'stripe-identity-react-native' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo managed workflow
 Error: Requiring module "node_modules/@stripe/stripe-identity-react-native/src/index.ts", which threw an exception: Error: The package 'stripe-identity-react-native' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```

**Comment by adscud** [comment]
It shouldn't be used in a `managed` workflow, you should use the dev client.
The managed workflow with ExpoGo can only works with packages include inside Expo Go.

**Comment by ribbonhood** [comment]
Just so I'm clear, @adscud are you saying this only works with the bare workflow with expo? Curious, what makes it all different from `"@stripe/stripe-react-native"` to need this?

**Comment by adscud** [comment]
The fault is not from the stripe package. 
When you using ExpoGo, you are limited with native packages because Expo Go is shipped with defined native packages, and you can't add more. 
If you want to, you have to move from the `managed workflow` to the `bare workflow` with the custom dev client.

**Comment by ribbonhood** [comment]
Well I wasn't using expo go, just run using pre building then using `expo run android` which I guess is the managed workflow. Managed to get it working though using running react native commands. It's still not really clear how these two would behave differently especially given that they're both using the android folder created by `expo prebuild`

**Comment by mvanroon** [comment]
Expo support for managed workflow builds could be added by adding an [expo-plugin](https://docs.expo.dev/modules/config-plugin-and-native-module-tutorial/)
