### ISSUE TITLE
Duplicate class com.stripe.android.uicore.address.AddressRepository_Factory error

### ISSUE THREAD

**Issue by hsb1007** [stripe/stripe-identity-react-native#121]
Hi when I build react native on android, I am getting below error message.

Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.stripe.android.uicore.address.AddressRepository_Factory found in modules jetified-identity-20.24.0-runtime (com.stripe:identity:20.24.0) and jetified-link-20.24.0-runtime (com.stripe:link:20.24.0)

I know there was a discussion around this exact error in the below thread, which is supposedly fixed in the latest version.
However, I am still getting the error, is anyone facing the same issue?

https://github.com/stripe/stripe-android/issues/6590

**Comment by ccen-stripe** [comment]
Hi @hsb1007 , thanks for reporting this, we just released [0.1.8](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.8) with a fix to this problem. Please try with the new version and feel free to reopen if you still have issue with the build:)

**Comment by hsb1007** [comment]
Yup after upgrading stripe-identity-react-native and stripe-react-native to 0.1.8 and 0.27.2 respectively, it is now working! 

Thank you!
