### ISSUE TITLE
How to combine required styles.xml with existing styles.xml ?

### ISSUE THREAD

**Issue by abdullahIsa** [stripe/stripe-identity-react-native#123]
Hello i have this in my current styles.xml

```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:textColor">#000000</item>
        <item name="colorPrimary">@color/colorPrimary</item>
    </style>
    <!-- BootTheme should inherit from Theme.SplashScreen -->
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
        <!-- Status bar initial style: true = dark-content, false = light-content -->
        <item name="android:windowLightStatusBar">true</item>
        <!-- Navigation bar will stay translucent on Android < 8.1 -->
        <item name="android:windowTranslucentNavigation">true</item>
    </style>
</resources>
```

and i am not sure how to correctly add the required part

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
</style>
```

In AndrodManifest.xml i use ``android:theme="@style/BootTheme"``

how to correctly add together ?

**Comment by abdullahIsa** [comment]
A little more context

stripe-identity-react-native required to set android:theme="@style/AppTheme" but "@style/AppTheme" default is to use "parent="Theme.AppCompat.Light.NoActionBar" but stripe-identity-react-native required to change it to "Theme.MaterialComponents.Light.NoActionBar" 
and if i changed to "Theme.MaterialComponents.Light.NoActionBar" then app cant build

**Comment by abdullahIsa** [comment]
Hello anyone can help with this ?

**Comment by ccen-stripe** [comment]
hi @abdullahIsa, the React native SDK wraps Identity's Android SDK, which requires Material theme to build as it uses some material libraries, please refer to [this doc](https://stripe.com/docs/identity/verify-identity-documents?platform=android&type=new-integration#set-up-material-theme) for more details

If your app can't build after changing the theme to `Theme.MaterialComponents.*`, I would recommend migrating to Material theme from AppCompat, just got some pretty thorough guidance from this [quick search](https://www.google.com/search?q=migrate+to+material+theme+from+AppCompat&oq=migrate+to+material+theme+from+AppCompat&aqs=chrome..69i57j69i64l2.6095j0j7&sourceid=chrome&ie=UTF-8)

**Comment by abdullahIsa** [comment]
> hi @abdullahIsa, the React native SDK wraps Identity's Android SDK, which requires Material theme to build as it uses some material libraries, please refer to [this doc](https://stripe.com/docs/identity/verify-identity-documents?platform=android&type=new-integration#set-up-material-theme) for more details
> 
> If your app can't build after changing the theme to `Theme.MaterialComponents.*`, I would recommend migrating to Material theme from AppCompat, just got some pretty thorough guidance from this [quick search](https://www.google.com/search?q=migrate+to+material+theme+from+AppCompat&oq=migrate+to+material+theme+from+AppCompat&aqs=chrome..69i57j69i64l2.6095j0j7&sourceid=chrome&ie=UTF-8)

Hello i already moved on with a different identity provider, will close this issue, thanks.
