### ISSUE TITLE
identity verification modal not showing

### ISSUE THREAD

**Issue by sharifashraful** [stripe/stripe-identity-react-native#132]
Please check the video. why identity verification modal not showing

"@stripe/stripe-identity-react-native": "^0.1.8",
"@stripe/stripe-react-native": "0.27.2",
"@stripe/stripe-terminal-react-native": "^0.0.1-beta.12",

https://github.com/stripe/stripe-identity-react-native/assets/7131239/60d52d14-917a-49fb-858e-9f03f0c06aac

**Comment by ccen-stripe** [comment]
Hi @sharifashraful could you share your iOS error log?

**Comment by sharifashraful** [comment]
@ccen-stripe fixed.

verification modal not showing when i use 'react-native-loading-spinner-overlay'
