### ISSUE TITLE
[iOS/Android] missing translation for French language

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-identity-react-native#137]
Hi all! Translation is missing for this screen for French language and maybe for other!

```
    "@stripe/stripe-identity-react-native": "0.2.1",
    "@stripe/stripe-react-native": "0.31.1"
```

![IMG_2246](https://github.com/stripe/stripe-identity-react-native/assets/65358122/f7ba36ef-a39e-499d-ab50-40498481034b)

**Comment by ccen-stripe** [comment]
Hi @nicolasdevienne this is a new screen we recently introduced and translation should be available soon, will update in the ticket when translation is available.

**Comment by ccen-stripe** [comment]
fixed in https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.2.2
