### ISSUE TITLE
[iOS] testmode page already returns "FlowCanceled"

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-identity-react-native#138]
Hi all! When we choose one of the item in choices list on test mode page for iOS (Verification success, Verification failure, ...), the SDK already returns "FlowCanceled".

![Simulator Screenshot - iPhone 15 Pro - 2023-09-20 at 18 00 55](https://github.com/stripe/stripe-identity-react-native/assets/65358122/9030fb93-da3b-40c4-8fb7-207636bcdb1b)

**Comment by ccen-stripe** [comment]
hi @nicolasdevienne thanks for flagging this! I identified this is an issue on the native iOS SDK. Will send a fix and update here when fix is released.

Please note this doesn't affect you running the SDK normally - if you go through the flow through `Proceed` SDK would return 'FlowCompleted' correctly

**Comment by ccen-stripe** [comment]
Fixing in https://github.com/stripe/stripe-ios/pull/2988

**Comment by ccen-stripe** [comment]
fixed in https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.2.2
