### ISSUE TITLE
[Android] brand logo is missing on the top of the screen

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-identity-react-native#139]
Hi all! Brand logo is missing on the top left of the screen for Android. For iOS it works!

![logo android](https://github.com/stripe/stripe-identity-react-native/assets/65358122/91dc6049-a7bc-4ac6-b769-9b0c6a3a7fc6)

**Comment by ccen-stripe** [comment]
hi @nicolasdevienne could you double check the asset is in `.png` format is loaded correctly? [Here](https://github.com/stripe/stripe-identity-react-native/blob/a4ea79c31c73ef2ee0a08737ded64d32ece7dbc4/example/src/screens/HomeScreen.tsx#L41C2-L41C2) is how the logo is correctlyed loaded in the example app, you could verify that by executing `yarn android` under the [example](https://github.com/stripe/stripe-identity-react-native/tree/main/example) dir

**Comment by nicolasdevienne** [comment]
> hi @nicolasdevienne could you double check the asset is in `.png` format is loaded correctly? [Here](https://github.com/stripe/stripe-identity-react-native/blob/a4ea79c31c73ef2ee0a08737ded64d32ece7dbc4/example/src/screens/HomeScreen.tsx#L41C2-L41C2) is how the logo is correctlyed loaded in the example app, you could verify that by executing `yarn android` under the [example](https://github.com/stripe/stripe-identity-react-native/tree/main/example) dir

Thx @ccen-stripe! My image was in res/drawable folder for Android but I change as you tell me and now it works!

**Comment by nicolasdevienne** [comment]
Hi @ccen-stripe, I have just discover that on Android simulator the image is present but missing on a real device...

**Comment by ccen-stripe** [comment]
hey @nicolasdevienne could you retry with the example app [here](https://github.com/stripe/stripe-identity-react-native/tree/main/example)? I just built it on a real device pixel-5 and it seems working fine:

![deviceRecording](https://github.com/stripe/stripe-identity-react-native/assets/79880926/18bb3627-7d14-4c21-a7db-0b1af92c3a8d)

**Comment by nicolasdevienne** [comment]
Hi @ccen-stripe as you can see on the following screens, on simulator it's OK but KO on real device. I don't understand. For iOS it's OK for the two ways : simulator and real device.

![Screenshot_1702050544](https://github.com/stripe/stripe-identity-react-native/assets/65358122/f6999403-c77c-4828-8227-364f2582f939)
![Screenshot_20231208-170106](https://github.com/stripe/stripe-identity-react-native/assets/65358122/e4aba8b6-afa7-4e03-8734-9f97e8acb783)

My code is very simple :

```
import brandLogo from '../../../../../assets/shared/images/medadom_icon.png';
...
await presentIdentityVerificationSheet({ sessionId, ephemeralKeySecret, brandLogo: Image.resolveAssetSource(brandLogo) });

```

Also I notice that the text are not in French language. Can you translate it in the next version please?

**Comment by ccen-stripe** [comment]
hi @nicolasdevienne FR translation should be ready now, you don't need to upgrade the SDK version as it comes from our backend. 
Re. image not showing up, could you verify this issue is reproducible with your device from our [example android app](https://github.com/stripe/stripe-identity-react-native/tree/main/example) ? I tried with a couple of physical devices but cannot reproduce it.

**Comment by ccen-stripe** [comment]
following up in https://github.com/stripe/stripe-identity-react-native/issues/156
