### ISSUE TITLE
[Android] change color for dark mode

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-identity-react-native#140]
Hi all! On Android, for dark mode, some texts blend in with the background color (black on black background) and the header, unlike light mode, is not the same color as the buttons. I can also change the color but the headband remains gray.

![mode clair + couleur défaut](https://github.com/stripe/stripe-identity-react-native/assets/65358122/3c27a5a5-fc8a-483d-af82-372e3698a50b)
![mode sombre + couleur défaut](https://github.com/stripe/stripe-identity-react-native/assets/65358122/efb19ba2-b2d1-4ec0-bbde-2d2ddbd317f6)

**Comment by ccen-stripe** [comment]
Hi @nicolasdevienne thanks for flagging this, we will fix this in our next release!

**Comment by ccen-stripe** [comment]
fixing in https://github.com/stripe/stripe-android/pull/7573

**Comment by ccen-stripe** [comment]
Fixed since [20.35.0](https://github.com/stripe/stripe-android/releases/tag/v20.35.0)
