### ISSUE TITLE
[iOS/Android] retrieve data in VerificationReport object

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-identity-react-native#144]
Hi all! We would like to retrieve data "sexe" and "lieu de naissance" in VerificationReport object for French ID Card as you can see on the following screen.

![phpCDwGn0](https://github.com/stripe/stripe-identity-react-native/assets/65358122/bcd50914-b6f3-4e04-ac40-509e81a9ba20)

**Comment by ccen-stripe** [comment]
hi @nicolasdevienne unfortunately we didn't support exposing these data for now, could you reach out to our sales team and schedule a call with us? happy to walk over your usecases and see if we could support this feature
