### ISSUE TITLE
[iOS/Android] missing item from ID Card choices

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-identity-react-native#145]
Hi all! Item "Titre de séjour" is missing from the following choices.

![IMG_2504](https://github.com/stripe/stripe-identity-react-native/assets/65358122/948f3e5f-c3eb-4840-9e68-2d007a87df3e)

**Comment by ccen-stripe** [comment]
Hi @nicolasdevienne, we support 3 types of document: driver license, ID card and passport, where ID Card covers all types of government issued document. In your case "Titre de séjour" should belong to ID card, please see [here](https://stripe.com/docs/identity/verification-checks?type=document) for more details

**Comment by nicolasdevienne** [comment]
> Hi @nicolasdevienne, we support 3 types of document: driver license, ID card and passport, where ID Card covers all types of government issued document. In your case "Titre de séjour" should belong to ID card, please see [here](https://stripe.com/docs/identity/verification-checks?type=document) for more details

Hi @ccen-stripe! Maybe it's possible to rename "Carte d'identité" by "Carte d'identité/Titre de séjour"? Just a suggestion. Regards.

**Comment by ccen-stripe** [comment]
hi @nicolasdevienne we deliberated uses the generic term "ID card" to cover all types of ID card.

That said, we're currently working on improving the UI of the flow by removing the ID type selection screen(ETA end of this year), later user won't need to select type, we'll automatically detect the type of document in the scan screen.

Closing this ticket for now, if you have additional questions please feel free to reopen it.
