### ISSUE TITLE
[iOS/Android] Appearance customization

### ISSUE THREAD

**Issue by rafirr** [stripe/stripe-identity-react-native#148]
Hello everyone,

I have been researching the SDK and I understand that it utilizes the native Android and iOS SDK. However, I am curious if there is an option to customize the appearance of the elements, similar to the Elements Appearance API
https://stripe.com/docs/elements/appearance-api?platform=react-native. Alternatively, is there another way to customize basic elements such as colors, fonts and border-radius?

**Comment by ccen-stripe** [comment]
hi @rafirr , both Identity's Android and iOS SDK tries to read theme from the native app automatically, (specifically on Android - reading from the native [themes.xml](https://github.com/stripe/stripe-android/blob/master/identity-example/src/main/res/values/themes.xml)), at the moment there is no option to set the themes programtically from the API itself.
