### ISSUE TITLE
[Android] App crashes on card scanning PaymentSheet

### ISSUE THREAD

**Issue by nicolasdevienne** [stripe/stripe-identity-react-native#149]
**Describe the bug**

We recently added [stripe-identity-react-native](https://github.com/stripe/stripe-identity-react-native) SDK in our Android app and we discovered that card scanning PaymentSheet does not work anymore : app crashes.

**To Reproduce**

1. add `implementation 'com.stripe:stripecardscan:20.3.+'` in android/app/build.gradle file
2. add `@stripe/stripe-identity-react-native SDK`
3. invoke `PaymentSheet`
4. click on "scan card"

**Expected behavior**

App should not crash

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Version : last version for the 2 SDK

@ccen-stripe @charliecruzan-stripe

**Comment by ccen-stripe** [comment]
hi @nicolasdevienne , could you try include stripecardscan as follows?
```
implementation('com.stripe:stripecardscan:$stripeVersion') {
  exclude group: 'com.stripe', module: 'ml-core-cardscan' // exclude the cardscan-specific portable tflite runtime
}
```

Both Identity and cardscan use `ml-core-xxx`. Identity already includes `ml-core-default`, which is a superset of `ml-core-cardscan`. So we need to exclude it to avoid the duplicate class issue.

**Comment by nicolasdevienne** [comment]
> hi @nicolasdevienne , could you try include stripecardscan as follows?
> 
> ```
> implementation('com.stripe:stripecardscan:$stripeVersion') {
>   exclude group: 'com.stripe', module: 'ml-core-cardscan' // exclude the cardscan-specific portable tflite runtime
> }
> ```
> 
> Both Identity and cardscan use `ml-core-xxx`. Identity already includes `ml-core-default`, which is a superset of `ml-core-cardscan`. So we need to exclude the later to avoid the duplicate class issue.

Hi @ccen-stripe! I changed $stripeVersion by 20.35.+ and it works! Thank you!
