### ISSUE TITLE
Android doesn't display the brandLogo

### ISSUE THREAD

**Issue by googol7** [stripe/stripe-identity-react-native#156]
```
"@stripe/stripe-identity-react-native": "^0.2.5",
"react": "18.2.0",
"react-native": "0.72.5",
```

The built and released Android app doesn’t show the `brandLogo`:

![Android physical](https://github.com/stripe/stripe-identity-react-native/assets/282412/eeea8fa4-848b-4a1d-9520-73382eefe3c3)

The virtual device / Android Studio simulator shows the logo - but it’s too big:
![Android virtual](https://github.com/stripe/stripe-identity-react-native/assets/282412/d411f905-c281-4d90-bed8-a07d2003b2af)

The built and released iOS shows the logo in the correct size:
![iOS physical](https://github.com/stripe/stripe-identity-react-native/assets/282412/d9919326-20bc-4387-ae07-d7fcd41eedc4)

**Comment by googol7** [comment]
@ccen-stripe Can you reproduce this problem?

**Comment by nicolasdevienne** [comment]
> @ccen-stripe Can you reproduce this problem?

Hi @googol7 same here: https://github.com/stripe/stripe-identity-react-native/issues/139

**Comment by ccen-stripe** [comment]
hi @googol7 and @nicolasdevienne could you verify if your local environment is similar to our example app [here](https://github.com/stripe/stripe-identity-react-native/tree/main/example) and logo is loaded [here](https://github.com/stripe/stripe-identity-react-native/blob/10c031c0f585a8ff02cc02a41a29050b39a4b7e7/example/src/screens/HomeScreen.tsx#L41)? 

You can try clone the repo and run `yarn android` under the example folder to test the android integration, [this](https://github.com/stripe/stripe-identity-react-native/pull/164) was just recorded on a real pixel 5 device

**Comment by googol7** [comment]
@ccen-stripe We do it exactly like you do it in the example app:

`brandLogo: Image.resolveAssetSource(logo),`

IMPORTANT: It's not sufficient to run it locally! You need to build the app and then run the bundle (e.g. by releasing it to closed testing). Can you try that please? Can you confirm the problem then?

**Comment by ccen-stripe** [comment]
fixed in https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.2.10
