### ISSUE TITLE
Missing German translation on Android

### ISSUE THREAD

**Issue by googol7** [stripe/stripe-identity-react-native#162]
Using stripe-identity-react-native version 0.2.5 for Android and iOS.

### On Android we see:
**Make sure you're in a well-lit space.**

![Android Native 1](https://github.com/stripe/stripe-identity-react-native/assets/282412/03929a7a-94e8-4632-a5b8-ba3cec428b80)

### On iOS it's translated to German:
**Sorgen Sie für ausreichende Beleuchtung.**

![iOS Native](https://github.com/stripe/stripe-identity-react-native/assets/282412/1b84ec80-c6b4-4dd7-82e8-1012fda0d5b1)

**Comment by ccen-stripe** [comment]
hi @googol7 thanks for reporting this, the [android translation](https://github.com/stripe/stripe-android/pull/8314/files) was just merged recently, it should come with the next native release(`24.41.2`, which should land on Apri, 29), you can could build with the latest react native ([0.2.8](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.2.8)) to pick it up when 20.41.2 is available.

**Comment by googol7** [comment]
@ccen-stripe I cannot see the English string "Make sure you're in a well-lit space." in the [translations](https://github.com/stripe/stripe-android/pull/8314/files#diff-39f34d92bc67941ca124537afacb7cba1f4422a22f802781a49a1ef991f0a116) you mentioned.

**Comment by ccen-stripe** [comment]
sorry the string is actually added [here](https://github.com/stripe/stripe-android/blame/8c42e6083181552a33590305dac782c2b9319b98/identity/res/values-de/strings.xml#L84) last month, it's currently in 24.40.0, so if you upgrade the 0.2.8 now, should be able to get the translation.
