### ISSUE TITLE
Could not find ml-core-base-20.44.0.jar when building Android

### ISSUE THREAD

**Issue by Prakosa** [stripe/stripe-identity-react-native#165]
I have use stripe-identity-react-native version 0.2.9 but then when building it in Android Studio.

I always got this error

`Could not find ml-core-base-20.44.0.jar (com.stripe:ml-core-base:20.44.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/stripe/ml-core-base/20.44.0/ml-core-base-20.44.0.jar`
         

<img width="838" alt="Screenshot 2567-05-23 at 17 06 18" src="https://github.com/stripe/stripe-identity-react-native/assets/30237000/f5caa7b4-b3e0-41a3-a2b7-7acf10c988a4">

any idea on how to resolve this? thanks

I saw the update is made 2 days ago and they update it but didnt know if it breaks the previous version too

**Comment by ccen-stripe** [comment]
Hi @Prakosa , please make sure you are using the compatible version of `stripe-identity-react-native` and `stripe-react-native`, please  see details [here](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.2.10) in the release notes

**Comment by Prakosa** [comment]
I am using jcenter in my gradle build. I filter it by using only the library that using jcenter. Now its working already thanks @ccen-stripe
