### ISSUE TITLE
after installing no code in nom module 

### ISSUE THREAD

**Issue by waltershub** [stripe/stripe-identity-react-native#73]
this is is the readme 
# Security holding package

This package contained malicious code and was removed from the registry by the npm security team. A placeholder was published to ensure users are not affected in the future.

Please refer to www.npmjs.com/advisories?search=stripe-identity-react-native for more information.

**Comment by ruben-stripe** [comment]
Thanks for sharing. Our package in npm is `@stripe/stripe-identity-react-native` (no `stripe-identity-react-native`). Sorry for the confusion.
