### ISSUE TITLE
appCrash when useStripeIdentity called

### ISSUE THREAD

**Issue by UmarLE** [stripe/stripe-identity-react-native#80]
Thread 1 Crashed::  Dispatch queue: com.facebook.react.StripeIdentityReactNativeQueue

**Comment by AtaMuhiuldin** [comment]
Facing same issue.

**Comment by m-maaz-azhar** [comment]
Facing same issue on Android 10

**Comment by jpetrantoni** [comment]
Facing same issue. Cannot get sdk to work at all

**Comment by ccen-stripe** [comment]
Hi :wave thanks for the interest in our react native SDK! It is currently in beta and would require us to add your merchant to work, please send an email to [identity-mobile-sdk-beta@stripe.com](mailto:identity-mobile-sdk-beta@stripe.com) with your merchant information and we'll work with you to integrate the SDK.

**Comment by ccen-stripe** [comment]
Close due to inactivity

**Comment by hugoh59** [comment]
I'm still getting this issue.
