### ISSUE TITLE
Branding not being applied.

### ISSUE THREAD

**Issue by muhammadshaheer-er** [stripe/stripe-identity-react-native#91]
The branding added from settings does not get applied to the modal that pops up.

**Comment by ccen-stripe** [comment]
Hi @muhammadshaheer-er , sorry for the delay but we just fixed this in https://github.com/stripe/stripe-android/pull/6341, the Android release should be out on Monday, 13, 2023. Updating to the latest [0.1.4](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.4) by then should resolve this issue. Thanks!
