### ISSUE TITLE
Operation Could Not be completed (StripeIdentity.VerificationSheetFlowControllerError error 1)

### ISSUE THREAD

**Issue by jthettleman** [stripe/stripe-identity-react-native#98]
Current Versions:
- stripe-identity-react-native (0.1.1):
    - React-Core
    - StripeIdentity (~> 22.1)
  - StripeCameraCore (22.8.2):
    - StripeCore (= 22.8.2)
  - StripeCore (22.8.2)
  - StripeIdentity (22.8.2):
    - StripeCameraCore (= 22.8.2)
    - StripeCore (= 22.8.2)
    - StripeUICore (= 22.8.2)
  - StripeUICore (22.8.2):
    - StripeCore (= 22.8.2)

Creating VerificationSession with Selfie capture required and documents

Steps to reproduce:
Create verification session with type document, and selfie enabled
Go through whole process on mobile app
Wait until the response is "Requires Input" with any error (in my case it was a selfie mismatch)
Retrieve the verification session and create new ephemeral key
Start verification process and click driver's license again

!!! Flow goes immediately to selfie
!!! Take selfie
!!! Goes to error screen and says: Operation Could Not be completed (StripeIdentity.VerificationSheetFlowControllerError error 1)

Anyone know why this happens?

**Comment by ccen-stripe** [comment]
hi @jthettleman thanks for reporting, we are taking a look and will update here

**Comment by ccen-stripe** [comment]
Hi @jthettleman, we just released [0.1.4](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.4), could you verify this error still persists? thanks!

**Comment by ccen-stripe** [comment]
Closing the issue for now, feel free to reopen if you still see issues

**Comment by interstellrau** [comment]
This issue is still occurring on 0.2.13, instead with the error

Operation Could Not be completed (StripeIdentity.VerificationSheetFlowControllerError error 3)

**Comment by IAmInControll** [comment]
Hi, I am encountering the same issue as @interstellrau . A lot of my iOS users have reported encountering this error directly after taking a selfie (scan identity document -> take selfie -> see error). This issue is making the app inaccessible to a lot of my users. 

@ccen-stripe any updates on this issue would be highly appreciated thanks.
