### ISSUE TITLE
App crashes on present()

### ISSUE THREAD

**Issue by giaset** [stripe/stripe-identity-react-native#99]
Hey all,

We've been using Identity's hosted/redirect flow in our Expo app for almost a year and are huge fans. We're trying to switch to the native SDK, but the app crashes with no errors the second we call `present()`.

Here's what our implementation looks like. It's basically verbatim from the docs. (And yes, `NSCameraUsageDescription` is set in our Info.plst!)

```
const fetchOptions = useCallback(async () => {
    const {
      createVerificationSession: { verificationSession }
    } = await fetchVerificationSession();
    return {
      brandLogo: Image.resolveAssetSource(ICON),
      ephemeralKeySecret: verificationSession.ephemeralKeySecret,
      sessionId: verificationSession.externalId
    };
  }, [fetchVerificationSession]);

  const { error, loading, present, status } = useStripeIdentity(fetchOptions);

  const onPress = useCallback(() => {
    present();
  }, [present]);
```

`loading` briefly goes to true before switching back to false. `error` and `status` always stay `undefined`, and then the app crashes... Any ideas?

**Comment by giaset** [comment]
We've also enabled the Native Mobile SDK beta in our dashboard. Note that this is crashing in a test environment, does that make a difference? Thanks!

<img width="487" alt="Screen Shot 2023-02-17 at 4 47 21 PM" src="https://user-images.githubusercontent.com/2816603/219822187-ab468973-e63a-4920-a231-eba0d23ca57b.png">

**Comment by giaset** [comment]
After some digging (prebuilding the app using `expo prebuild` and running it directly from XCode), I've found the issue

```
StripeIdentity/IdentityVerificationSheet.swift:160: Fatal error: presentingViewController is already presenting a view controller
```

Our signup flow is presented modally, and it seems like the SDK guards against presenting the Identity Verification modal if another view controller is already presented modally. This strikes me as an... odd restriction, as many signup flows are presented modally. Any suggestions on how to work around this? Thanks again!

**Comment by ccen-stripe** [comment]
hi @giaset thanks for reporting the error, the reason of the crash is the `presentingViewController` passed from iOS is already presenting another modal(say modal1). Without dismissing modal1 first, `presentingViewController` can't present another modal(say modal2), and all the Identity flow is built on top of modal2.

To clarify, 

This is OK ⬇️  - identity will create a new modal on top of the viewController2's modal
```
viewController1.present(viewController2, false)
identityVerificationSheet.present(from: viewController2, completion:...)
```
------------

This will crash ⬇️ , can't present two modals on viewController1
```
viewController1.present(viewController2, false)` // then without dismissing `viewController2`
identityVerificationSheet.present(from: viewController1, completion:...)
```

If I remove the check within our SDK, the iOS system will send such error silently
```
2023-02-17 18:05:47.819754-0800 IdentityVerificationExample[2400:1103433] [Presentation] Attempt to present <StripeIdentity.IdentityFlowNavigationController: 0x10482c600> on <UINavigationController: 0x10281e800> (from <IdentityVerificationExample.viewController1: 0x104808c00>) which is already presenting <IdentityVerificationExample.ViewController2: 0x10500fb20>.
```

**Comment by ccen-stripe** [comment]
Not sure how your app ends up in this state on iOS, but I would suggest checking out our [example](https://github.com/stripe/stripe-identity-react-native/blob/main/example/src/screens/HomeScreen.tsx), where we build a screen and button on RN to trigger the flow

**Comment by giaset** [comment]
Thanks for the quick response @ccen-stripe! I understand *how* you've implemented that check, I still don't really understand *why*, as presenting multiple modals is an extremely common flow in iOS apps (this is true since at least iOS 13, maybe even before). It just seems like an extremely weird restriction. Attached is a video of our flow, which you'll note is super standard.

1) User is on the home screen
2) User taps on the deposit button in the top right to load their account with money
3) The deposit flow is presented modally (standard). Because they've yet to go through identity verification, they're presented with a screen explaining the verification process
4) They press the Verify Identity button to kick off the Stripe flow
5) The app crashes instantly

https://user-images.githubusercontent.com/2816603/219875708-33377e9b-324d-467a-8a8f-26c454920b3b.mov

**Comment by giaset** [comment]
One important thing to note: this is an Expo app using react-navigation. Perhaps this is messing with what iOS thinks the `presentingViewController` is? (I'd be surprised, as it's one of the most commonly used RN libraries and is fairly bullet-proofed at this point)

**Comment by ccen-stripe** [comment]
@giaset From the recording it does seem `presentingViewController` passed to the API is the VC for the home screen, but not the VC of the "Let's get you verified ..." screen, which would cause the crash.

If you have access to iOS code, you could try make a call `homeScreenVC.present(anotherVC, animated: false)` while "Let's get you verified" modal is visible - you'll see an iOS system error. As I tested above, since we're also using the `present` function within our SDK, if the check is removed you'll see the same system error

**Comment by giaset** [comment]
Sorry @ccen-stripe -- I've been away on travel and just re-visiting this now.

The implementation on our end and on react-navigation's end is correct. The mistake is on Stripe's end: https://github.com/stripe/stripe-identity-react-native/blob/ef99cf9625b8d34617e4e15a26312daa7f98d426/ios/StripeIdentityReactNative.swift#L42

It doesn't seem reasonable to always set `UIApplication.shared.delegate?.window??.rootViewController` as the `presentingViewController` -- this precludes any flow that is presented modally from ever working.

In our case, the `rootViewController` is our root navigation controller. We then present that "Let's get you verified..." screen modally, so this assertion will always fail: https://github.com/stripe/stripe-ios/blob/11cdf2d0a836b21a76d3c77cc7db8b8b3254192a/StripeIdentity/StripeIdentity/Source/IdentityVerificationSheet.swift#L159

(Recall: `presentedViewController` is the "Let's get you verified..." screen, in our case)

I should be able to patch this locally to get it unblocked on our end. If I have time, I can maybe put together a PR at some point

**Comment by giaset** [comment]
I ended up patching my package locally and doing this, which works great and is sufficient for my needs:

```
@objc func presentIdentityVerificationSheet(_ resolve: @escaping RCTPromiseResolveBlock, rejecter reject: @escaping RCTPromiseRejectBlock) {
        DispatchQueue.main.async {
            var presentingViewController = UIApplication.shared.delegate?.window??.rootViewController ?? UIViewController()
            while let presentedViewController = presentingViewController.presentedViewController {
                presentingViewController = presentedViewController
            }
            self.verificationSheet?.present(
                from: presentingViewController,
                completion: { result in
                    switch result {
                    case .flowCompleted:
                        resolve(["status": "FlowCompleted"])
                    case .flowCanceled:
                        resolve(["status": "FlowCanceled"])
                    case .flowFailed(let error):
                        resolve([
                            "status": "FlowFailed",
                            "error": createError("FlowFailed", error as NSError)
                        ])
                    }
                })
        }
    }
```

**Comment by ccen-stripe** [comment]
thanks for the report, just had a fix https://github.com/stripe/stripe-identity-react-native/pull/103 for the upcoming 0.1.3 release
